from __future__ import annotations

SSDP_DISCOVERY_TIMEOUT_SEC = 5
NETWORK_SCAN_RETRY_SEC = 60
NETWORK_SCAN_TIMEOUT_SEC = 0.6
NETWORK_SCAN_MIN_NETMASK = 24
NETWORK_SCAN_MAX_THREADS = 128
TOPOLOGY_SETTLE_ATTEMPTS = 75
TOPOLOGY_SETTLE_INTERVAL_SEC = 0.2
TOPOLOGY_QUERY_TIMEOUT_SEC = 2.0
PLAYBACK_QUERY_ATTEMPTS = 2
PLAYBACK_QUERY_RETRY_SEC = 0.08
SOURCE_CAPABILITY_RETRY_SEC = 300
ARTWORK_AVAILABILITY_TTL_SEC = 300
ARTWORK_AVAILABILITY_CACHE_LIMIT = 128


class ControllerError(RuntimeError):
    pass
