from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol


class StatePort(Protocol):
    def refresh(self, *, rediscover: bool = True) -> dict[str, Any]: ...

    def event_services(self) -> dict[str, Any]: ...

    def refresh_event_topologies(self, household_ids: Iterable[str]) -> None: ...


class PlaybackPort(Protocol):
    def play_pause(self) -> None: ...

    def play(self) -> None: ...

    def pause(self) -> None: ...

    def next(self) -> None: ...

    def previous(self) -> None: ...

    def seek(self, position_sec: Any) -> None: ...

    def move_playback_to_room(self, room_uid: str) -> None: ...


class ContentPort(Protocol):
    def play_favorite(self, favorite_id: str) -> None: ...

    def refresh_favorites(self) -> None: ...


class TopologyPort(Protocol):
    def select_group(self, group_uid: str) -> None: ...

    def select_room(self, room_uid: str) -> None: ...

    def apply_members(self, room_uids: list[str]) -> None: ...


class MixerPort(Protocol):
    def set_group_volume(self, volume: Any) -> None: ...

    def adjust_group_volume(self, delta: Any) -> None: ...

    def set_group_mute(self, mute: Any) -> None: ...

    def set_room_volume(self, room_uid: str, volume: Any) -> None: ...

    def adjust_room_volume(self, room_uid: str, delta: Any) -> None: ...

    def set_room_mute(self, room_uid: str, mute: Any) -> None: ...


class SonarchyBackendPort(StatePort, PlaybackPort, ContentPort, TopologyPort, MixerPort, Protocol):
    """Temporary adapter port implemented by the legacy controller."""
